### PR TITLE
Scopum

### PR DESCRIPTION
**Pull request by MacarenaGB**
Scopum is a new version created by Hacklab Upm Bq

### CODE REVIEW

**Comment by JavierIH** [comment]
This is really nice, thank you very much!

**Comment by Obijuan** [comment]
Thanks!!!!  :-)

**Comment by MacarenaGB** [comment]
We will improve it as soon as possible!

2015-04-15 8:36 GMT+02:00 Juan Gonzalez-Gomez <notifications@github.com>:

**Comment by Obijuan** [comment]
Your jedi powers are increasing, my young padawan. Keep up your training

**Pull request merged**
